-- ===========================================================
-- Clipboard history
--
-- What it does:
--   * Remembers the last things you copied (text only).
--   * Press Ctrl+Cmd+V (⌃⌘V) to open a searchable list; type to
--     filter, then Enter (or click) pastes that item into the app
--     you were using.
--   * Skips passwords copied from password managers (they mark
--     their clipboard items as secret).
--   * History is kept in memory only: nothing is written to disk,
--     and it's cleared when Hammerspoon restarts or reloads.
-- ===========================================================


-- ---------- Settings you can change ----------
local config = {
  maxItems  = 25,     -- how many copied items to remember
  hotkey    = { mods = { "ctrl", "cmd" }, key = "V" },
  autoPaste = true,   -- true = paste right away; false = only copy
                      -- it back to the clipboard (then press Cmd+V)
  -- Clipboard types that mean "secret, don't remember this"
  -- (used by 1Password, Bitwarden, Keychain, etc.)
  ignoreTypes = {
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
  },
}


local history = {} -- newest first: { text = ..., time = os.time() }


-- ---------- Remember what gets copied ----------
local function isSecret()
  for _, t in ipairs(hs.pasteboard.contentTypes() or {}) do
    for _, ignored in ipairs(config.ignoreTypes) do
      if t == ignored then return true end
    end
  end
  return false
end

local function add(text)
  if not text or text:match("^%s*$") then return end
  -- Copying the same thing again moves it to the top
  for i, h in ipairs(history) do
    if h.text == text then table.remove(history, i); break end
  end
  table.insert(history, 1, { text = text, time = os.time() })
  while #history > config.maxItems do table.remove(history) end
end


-- ---------- How items look in the list ----------
-- One line, max 80 characters
local function preview(text)
  local line = text:gsub("%s+", " "):gsub("^ ", "")
  local cut = utf8.offset(line, 81)
  if cut then line = line:sub(1, cut - 1) .. "…" end
  return line
end

-- "just now", "5 min ago", "2 h ago", "3 days ago"
local function ago(t)
  local s = os.time() - t
  if s < 60 then return "just now" end
  if s < 3600 then return math.floor(s / 60) .. " min ago" end
  if s < 86400 then return math.floor(s / 3600) .. " h ago" end
  return math.floor(s / 86400) .. " days ago"
end

local function buildChoices()
  if #history == 0 then
    return { { text = "Clipboard history is empty", subText = "Copy some text first", empty = true } }
  end
  local choices = {}
  for _, h in ipairs(history) do
    local length = utf8.len(h.text) or #h.text
    table.insert(choices, {
      text = preview(h.text),
      subText = ago(h.time) .. " · " .. length .. " characters",
      fullText = h.text,
    })
  end
  table.insert(choices, { text = "Clear clipboard history", subText = "Forget everything above", clear = true })
  return choices
end


-- ---------- The search list ----------
local pasteTimer
local chooser = hs.chooser.new(function(choice)
  if not choice or choice.empty then return end
  if choice.clear then
    history = {}
    hs.alert.show("Clipboard history cleared")
    return
  end
  hs.pasteboard.setContents(choice.fullText)
  if config.autoPaste then
    -- Give focus a moment to return to the previous app, then paste
    pasteTimer = hs.timer.doAfter(0.1, function()
      hs.eventtap.keyStroke({ "cmd" }, "v", 0)
    end)
  end
end)
chooser:placeholderText("Search clipboard history…")
chooser:rows(10)


-- ---------- Start everything ----------
-- (Stored in globals so macOS doesn't clean them up.)
clipboardChooser = chooser
clipboardWatcher = hs.pasteboard.watcher.new(function()
  if not isSecret() then add(hs.pasteboard.getContents()) end
end)
clipboardHotkey = hs.hotkey.bind(config.hotkey.mods, config.hotkey.key, function()
  chooser:choices(buildChoices())
  chooser:query("")
  chooser:show()
end)

-- Start with whatever is on the clipboard right now
if not isSecret() then add(hs.pasteboard.getContents()) end
